services:
  frontend:
    build:
      context: ./app/frontend
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - ./app/frontend:/app
    environment:
      - NODE_ENV=development
      - WATCHPACK_POLLING=true
      - CHOKIDAR_USEPOLLING=true
      - NEXT_PUBLIC_API_URL=http://localhost:8080
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1G
        reservations:
          cpus: '0.5'
          memory: 512M
    depends_on:
      backend:
        condition: service_healthy

  backend:
    build:
      context: ./app/backend
      dockerfile: Dockerfile.dev
    ports:
      - "8080:8080"
    volumes:
      - ./app/backend/src:/app/src
      - ./app/backend/build.gradle:/app/build.gradle
      - ./app/backend/settings.gradle:/app/settings.gradle
      - backend-gradle-cache:/root/.gradle
    environment:
      - SPRING_PROFILES_ACTIVE=dev
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1G
        reservations:
          cpus: '0.5'
          memory: 512M
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    image: postgres:16-alpine
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=tlogger
      - POSTGRES_USER=tlogger
      - POSTGRES_PASSWORD=tlogger
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U tlogger -d tlogger"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: unless-stopped

  frontend-node-cli:
    build:
      context: ./app/frontend
      dockerfile: Dockerfile.dev
    command: sh
    volumes:
      - ./app/frontend:/app

volumes:
  backend-gradle-cache:
  postgres-data:

networks:
  default:
    name: tlogger-network
    driver: bridge
