FROM eclipse-temurin:21-jdk

WORKDIR /app

COPY gradle gradle
COPY gradlew gradlew.bat ./
COPY build.gradle settings.gradle ./
RUN chmod +x ./gradlew
RUN ./gradlew --no-daemon dependencies

COPY src src

EXPOSE 8080

CMD ["./gradlew", "bootRun", "--no-daemon"]